INSERT INTO projects
(title, category, funding_goal, start_date, end_date) VALUES
("humor", "humor", 1000, "october 5", "october 9"),
("oh ya", "not humor", 2000, "october 1", "october 3"),
("oh no", "sometimes humor", 3000, "october 1", "october 9"),
("oh oh", "humor", 1000, "october 5", "october 9"),
("humor1", "not humor", 2000, "october 1", "october 9"),
("humor2", "sometimes humor", 3000, "october 1", "october 3"),
("humor3", "humor", 1000, "october 1", "october 3"),
("humor4", "not humor", 2000, "october 5", "october 9"),
("humor5", "sometimes humor", 3000, "october 1", "october 3"),
("humor6", "never humor", 5000, "october 1", "october 3");


INSERT INTO users (name) VALUES
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon"),
("marlon");

INSERT INTO pledges (amount) VALUES
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0),
(0);
